dist: xenial
language: python
python:
  -"3.7"
cache: pip
install:
  -pip install ibm_watson
install:
  -pip install data_processing
install:
  -pip install JSON
script:
  -python Middleware.py
language: node_js
node_js:
  - 8
cache:
  directories:
    - node_modules
script:
  - npm run build
  - npm test
