dist: xenial
language: python
python:
  - "3.7-dev"
cache: pip
addons:
  apt:
    sources:
        - deadsnakes
      packages:
        - python 3.5 
install:
  - pip install ibm_watson
script:
  - python Middleware.py
language: node_js
node_js:
  - 8
cache:
  directories:
    - node_modules
script:
  - npm run build
  - npm test
