dist: xenial
language: python
python:
  - "3.7"
cache: pip
before_install:
  - sudo apt-get install python3
install:
  - pip install ibm_watson
script:
  - python Middleware.py
language: node_js
node_js:
  - 8
cache:
  directories:
    - node_modules
script:
  - npm run build
  - npm test
